version: '3'
services:
  db:
    image: annalevina/mysql-bookstore
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"

  api:
    build: .
    environment:
      DATABASE_URL: "mysql://user:123@db:3306/bookstore"
    depends_on:
      - db
    ports:
      - "8002:8002"
