services:
  db:
    image: annalevina/mysql-bookstore
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    networks:
      - bookstore-network
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  api:
    build: .
    environment:
      DATABASE_URL: "mysql+mysqldb://user:123@db:3306/bookstore"
    depends_on:
      - db
    ports:
      - "8002:8000"
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge
